travis:
  secure:
    BINSTAR_TOKEN: lnJlRxpzT35qTex22+4opiyPx2Ul18EPPRpODF8YBbYiB7Vxh8+J1zui9Sx/fif1rW/onNauv3klniY0qCUwd1BthtP1vIfH4ld7bjZRTCwocArCEOmqvbzuUABD4Wgg5zNSsTxyISv8utDT389m8ZwQlZGAS5IIxJakMzK2m+Rdd2ScDcO3XdDWpHorOxpQmzdW0oWYA2BJFqlimwVmqIc/NoIMPYVdoFj39ZiKQUKANQm/kkMxnArZPebwR9+KBZCnP0eM3fB9/Mj+e92IgRQL5DnYbx0oRjOTgXZ0KrmdlTV1HFEkJmesqNdyW3q7GNSWM3yqyV4YzGalnvDGJMh02/PDbz53WTrVvZ9eQj/duoZrx8OmyeB28NymWehGW4aJtUecHz/O+R05WZ6bS7mm8tRIz2JpRRXB9fGlkTis3XqMIUZL6hsNYnRJB0P/PmRnVVyxrI6M0ZoWDNcZya1SNiI5VGJVvDKAx/EgG2Kp+vYrVpI7S6qkuwhLyG923bUtFTODq+/SIrmVAejLkfb+pQsEs1GTmSBHoJ/KLO8XY42N5QTXBw9hyK6wDoTm6t1eaSo7CM64uKlcU7nRo/1BbbaVUyzQw8SAnsDNQQJsCbT88/JI0meYbOe4/rXbLiQ4Q8BHb+YvA20VFDinLoMEbCYgLxTOzph8mw4GH9c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
